zilliztech/deep-searcher

.gitignore, README.md
=> Update .gitignore to include database files and add Q&A section to README

deepsearcher/agent/search_vdb.py, deepsearcher/online_query.py
This change implements parallel search for vector database queries using Python's asyncio to improve search efficiency.
- Converted serial search to parallel execution
- Added async query function `async_query`
- Maintained backward compatibility by keeping the sync `query` interface as a wrapper
- Implemented parallel search using `asyncio.gather`
- Maintained existing query logic and result processing flow
- Provided synchronous interface through `asyncio.run`
- Improved search performance
- No API changes, existing code calls remain unchanged
=> feat: implement parallel search using asyncio

README.md, deepsearcher/offline_loading.py, deepsearcher/vector_db/base.py, deepsearcher/vector_db/milvus.py, main.py
=> refactor: update type hints to use Union

README.md
=> docs: update README with troubleshooting steps for Hugging Face access issues and Jupyter notebook compatibility

README.md, deepsearcher/cli.py
Support loading multiple files and urls in one cmdline.
=> feat: enhance files loading in cli mode

config.yaml, deepsearcher/embedding/openai_embedding.py, deepsearcher/llm/openai_llm.py, examples/basic_example.py
=> feat: add support for base URL and embedding dimension configuration

deepsearcher/agent/rag_router.py, deepsearcher/llm/base.py
to fix : https://github.com/zilliztech/deep-searcher/issues/95 and https://github.com/zilliztech/deep-searcher/issues/95
=> robust LLM output parser for some corner cases

README.md, config.yaml, deepsearcher/loader/web_crawler/base.py, deepsearcher/loader/web_crawler/crawl4ai_crawler.py, deepsearcher/offline_loading.py
1. custom browser configuration https://docs.crawl4ai.com/core/browser-crawler-config/
2. add support for crawling multiple URLs https://docs.crawl4ai.com/advanced/multi-url-crawling/
=> Enhance Crawl4AI integration 

deepsearcher/cli.py
After merging zilliztech/deep-searcher#84, the answer is no longer output in cli mode.
=> Print final answer and references to CLI output

deepsearcher/embedding/siliconflow_embedding.py, deepsearcher/embedding/voyage_embedding.py
Embed multiple chunks in a single request
=> Support batch embedding in SiliconflowEmbedding

README.md, deepsearcher/cli.py, deepsearcher/vector_db/oracle.py
Old:
deepsearcher --load "your_local_path_or_url" --collection_name "your_collection_name" --collection_desc "your_collection_description"
New:
deepsearcher load "your_local_path_or_url" --collection_name "your_collection_name" --collection_desc "your_collection_description"
=> refactor: enhance CLI with subcommand using subparsers

deepsearcher/vector_db/oracle.py
use two tables to save collection information and vector items
=> fix oracle to store collection description

config.yaml, deepsearcher/embedding/__init__.py, deepsearcher/embedding/gemini_embedding.py
Gemini provides text embedding models, including `text-embedding-004` and `gemini-embedding-exp-03-07`, which can be added to this project.
=> Added support for Gemini text embedding models

deepsearcher/agent/chain_of_rag.py, deepsearcher/agent/collection_router.py, deepsearcher/agent/deep_search.py, deepsearcher/agent/naive_rag.py, deepsearcher/vector_db/milvus.py
=> Add dimension parameter to CollectionRouter and update invocations

README.md, deepsearcher/agent/chain_of_rag.py, deepsearcher/embedding/__init__.py, deepsearcher/embedding/glm_embedding.py, deepsearcher/llm/__init__.py, deepsearcher/llm/glm.py
Hi, it's a great project!
However, when I was debugging the code, I found a problem in the `chain_of_rag.py` file. That is, when `self.early_stopping` is set to `True`, it will stop regardless of whether the information is sufficient. But I think what is really intended here is to stop when the LLM determines that there is enough information, and continue to run when the information is insufficient.
Otherwise, if it stops regardless of whether the information is sufficient or not,  there is no need to call the `self._check_has_enough_info` function to determine whether the information is sufficient. 
So I adjusted the logic of the break.
=> fix the early stopping logic and support GLM_API

README.md, deepsearcher/embedding/glm_embedding.py, deepsearcher/llm/glm.py
Hi! You are right! In the code I submitted yesterday, both the LLM and Embedding of GLM were based on OpenAI, and there were overlapping parts with the existing code. So I changed the OpenAI library to ZhipuAI!
=> update ZhipuAI support

deepsearcher/embedding/volcengine_embedding.py
made some changes on volengine as follows:
1. added more embedding models.
2. updated params for existed embedding model.
/assign @xiaofan-luan
=> feat: updated volcengine embeddings.

config.yaml, deepsearcher/embedding/__init__.py, deepsearcher/embedding/fastembed_embdding.py, tests/test_fastembed.py
Hey 👋.
This PR adds support for generating vector embeddings using [FastEmbed](https://github.com/qdrant/fastembed) locally in Deep-Searcher.
Associated tests have been added.
=> feat: FastEmbed Embeddings

README.md, config.yaml, deepsearcher/vector_db/__init__.py, deepsearcher/vector_db/qdrant.py, tests/test_qdrant.py
Hey 👋
This PR adds support for using [Qdrant](https://qdrant.tech/) as the vector retrieval backend in Deep-Searcher.
Follow up https://github.com/zilliztech/deep-searcher/pull/171: feat: FastEmbed Embeddings
=> feat: Qdrant support

README.md, deepsearcher/embedding/ollama_embedding.py
=> fix: add batch size parameter to OllamaEmbedding initialization

README.md, deepsearcher/llm/__init__.py, deepsearcher/llm/aliyun.py
=> Feat: add Aliyun llm

deepsearcher/offline_loading.py
Update load_from_website() to include chunk_size and chunk_overlap parameters just like load_from_local_files()
=> Update load_from_website() to include chunk_size and chunk_overlap

deepsearcher/loader/web_crawler/firecrawl_crawler.py
Background  
The existing `FireCrawlCrawler` implementation was written against Firecrawl Python SDK ≤2.0.x and the legacy Firecrawl API. Since Firecrawl Python SDK v2.1.0 and the new V1 API:  
- Requests containing a top-level `params` payload are rejected (HTTP 400 “unrecognized_keys”).  
- The return types of `scrape_url()` and `crawl_url()` have changed from native `dict` to Pydantic `BaseModel` instances, which do not support `.get()`.  
These incompatibilities prevent `load_from_website()` from functioning with Firecrawl SDK ≥2.1.0.
Changes  
1. **Single-page scraping (`scrape_url`)**  
- Removed the `params={"formats": […]}` wrapper; now calls  
```python
self.app.scrape_url(url=url, formats=["markdown"])
```  
- Converts the returned Pydantic model to a dictionary via `.dict()`, …
=> fix(FireCrawlCrawler): adapt to Firecrawl v1+ API signature and Pydantic responses

examples/load_and_crawl_using_docling.py, examples/load_local_file_using_unstructured.py, examples/load_website_using_firecrawl.py
**Background**
Currently, the example files under "examples" do not have print outputs, which is not very beginner-friendly.
**Change**
Just add print for the final result
=> add print line in example

README.md, deepsearcher/embedding/openai_embedding.py, deepsearcher/vector_db/__init__.py, deepsearcher/vector_db/azure_search.py, examples/basic_example_azuresearch.py
Added support to do deep research with Azure AI Search Indexes.
Added support for Azure Open AI Embeddings.
Added support for Azure Open AI Models
=> Azure Search Vector DB and Azure Open AI Fixes for embeddings.

deepsearcher/vector_db/azure_search.py, pyproject.toml, uv.lock
- make azure lazily imported because it 's an optional dependencies
- update firecrawl-py >=2.3.0 because of the previous PRs: https://github.com/zilliztech/deep-searcher/pull/213  https://github.com/zilliztech/deep-searcher/pull/212
=> fix dependencies problem

deepsearcher/loader/file_loader/base.py
Load all supported files from a directory and its subdirectories recursively.
=> Load files recursively

README.md, deepsearcher/vector_db/milvus.py, docs/configuration/vector_db.md
This PR extends the Milvus vector database integration by adding support for additional connection configuration options, providing users with more flexibility when connecting to Milvus instances. Fixes #243 
-  Update Milvus connection parameters to support additional connection options
- Added configuration examples and guidelines for the new connection parameters
- `deepsearcher/vector_db/milvus.py` - Added support for other connection parameters aligned with the implementation of pymilvus `MilvusClient`.
- `docs/configuration/vector_db.md` - Updated documentation with new configuration options
- `README.md` - Updated documentation for Milvus configuration
None - this change is backward compatible with existing configurations.
=> Add support for other Milvus connection parameters
